/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String arg[]) {
    	System.out.println("Hello, World!");
    }
}
